### ISSUE TITLE
Persistent Storage on multiple zones

### ISSUE THREAD

**Issue by 524c** [isovalent/terraform-aws-talos#103]
Hello, 

Congratulations on the project.

I used this to deploy Talos Linux on AWS and everything went well. I am now looking for a Storage solution with replication support and visibility across all Nodes.

Do you have any suggestions for a storage option that would allow me to achieve this?

In my case I have 3 control-planes and 3 workers.

Thanks!

**Comment by PhilipSchmid** [comment]
Hi @524c,
Perfect to hear that this module works for you as well 🎉. We won't add a 3rd party persistent storage solution here. If one needs that, it should probably rather be installed via subsequent Terraform logic (e.g., a storage solution installed via [Terraform Helm provider](https://registry.terraform.io/providers/hashicorp/helm/latest/docs)). I'd probably have a look at [Longhorn](https://longhorn.io/), or [Rook](https://rook.io/) if you need more performance. Alternatively and perhaps even more preferred, I'd check out the official [AWS EBS CSI driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver) and simply start using AWS-native EBS storage. Keep in mind that the last one needs specific IAM permissions so "we" would need to implement support for that in this module - PRs welcome 😉.
